import '@/components/font';
import '@/components/theme';
import '@/components/layout';
import './page.scss';
import './_scroll/page_scroll_smooth.scss';
import './__body/page__body.scss';
import './__inner/page__inner.scss';
// import './__footer/page__footer.scss';
import './_view/page_view_default.scss';
export * from './page';
